<div class="container-fluid px-4">
    <h1 class="mt-4">Usuários</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/usuario">Usuários</a></li>
        <li class="breadcrumb-item active">Cadastrar</li>
    </ol>

    <!-- Formulario para cadastro do novo usuário -->

    <?php if (isset($this->view->status['status']) && $this->view->status['status']  == "ERROR") { ?>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>MENSAGEM: </strong> <?= $this->view->status['msg'] ?>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <?php } ?>

    <?php if (isset($this->view->status['status']) && $this->view->status['status']  == "SUCCESS") { ?>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>MENSAGEM: </strong> <?= $this->view->status['msg'] ?>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <?php } ?>

    <form action="/salvar_usuario" method="POST" enctype="multipart/form-data">

        <!-- Dados do usuário -->
        <div class="row">
            <div class="col-12 col-md-8 mb-3">
                <label for="nome" class="form-label">Nome</label>
                <input type="text" class="form-control" name="nome" value="<?= isset($this->view->tempUsuario['nome']) ? $this->view->tempUsuario['nome'] : ""; ?>" id="nome" title="digite o nome do usuário" required>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-8 mb-3">
                <label for="sobrenome" class="form-label">Sobrenome</label>
                <input type="text" class="form-control" name="sobrenome" value="<?= isset($this->view->tempUsuario['sobrenome']) ? $this->view->tempUsuario['sobrenome'] : ""; ?>" id="sobrenome" title="digite o sobrenome do usuário" required>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-8 mb-3">
                <label for="file_imagem" class="form-label">Envie um arquivo de imagem (Opcional)</label>
                <input type="file" name="file_imagem" id="file_imagem" class="form-control" accept="image/*">
            </div>
        </div>

        <!-- dados de login -->
        <div class="row">
            <div class="col-12 col-md-8 mb-3">
                <label for="email" class="form-label">E-mail</label>
                <input type="text" class="form-control" name="email" value="<?= isset($this->view->tempUsuario['email']) ? $this->view->tempUsuario['email'] : ""; ?>" id="email" title="digite o e-mail que será utilizado para login" required>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-5 mb-3">
                <label for="senha" class="form-label">Senha</label>
                <input type="password" class="form-control" name="senha" value="<?= isset($this->view->tempUsuario['senha']) ? $this->view->tempUsuario['senha'] : ""; ?>" id="senha" title="digite a senha do usuário" required>
            </div>
        </div>

        <?php
        $tipo = isset($this->view->tempUsuario['tipo']) ? $this->view->tempUsuario['tipo'] : '';  

        
       ?>

        

        <div class="row">
            <div class="col-12 col-md-5 mb-3">
                <label for="tipo" class="form-label">Tipo de usuário</label>
                <select class="form-select" name="tipo" aria-label="Default select example">
                    <option value=""                <?= $tipo == '' ? 'selected' : ''; ?> >Escolha uma opção</option>
                    <option value="Padrão"          <?= $tipo == 'Padrão' ? 'selected' : ''; ?> >Padrão</option>
                    <option value="Administrador"   <?= $tipo == 'Administrador' ? 'selected' : ''; ?> >Administrador</option>
                    <option value="Master"          <?= $tipo == 'Master' ? 'selected' : ''; ?> >Master</option>


                </select>
            </div>
        </div>


        <hr>

        <div class="row mt-3">
            <div class="col-12 col-md-6 mb-3">
                <input class="btn btn-primary" type="submit" value="Salvar" />
            </div>
        </div>
    </form>
</div>